merged the logfiles successfully
SChandrakanth15/LogAggregator pull request #1
Opened 2024-06-10 09:15 UTC by SChandrakanth15

Added the logic to read the file contents and do the processing and and released a background thread that will read all the file contents, merge all the log statements from multiple log files and sort it based on timestamp.

=> till merging completed(from different log files i have merged into one txt file.)

2024-06-10 09:53 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +public class LogAggregatorc {
incorrect spelling LogAggregatorc

2024-06-10 09:54 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +        if (!folder.exists() || !folder.isDirectory()) {
Move validations to separate class

2024-06-10 09:57 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +        while (processingThread.isAlive()) {
Thread is already executed, no use of looping over and printing dots

2024-06-10 10:01 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +import java.io.*;
Please mention the libraries imported instead *

2024-06-10 10:05 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +    public static void main(String[] args) {
Don't add lot of the business logics inside main().

2024-06-10 10:07 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +class ProcessingTask implements Runnable {
Rename the class ProcessingTask

2024-06-10 10:09 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +    private File folder;
Reduce usage of class level variables unless n until it is required

2024-06-10 10:12 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +        File[] files = folder.listFiles();
please keep proper naming 
explain is that input folder or output

2024-06-10 10:14 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +            try (FileWriter writer = new FileWriter("merged_logs.txt")) {
Strings should moved to constants

2024-06-10 10:16 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +        try {
Remove unnecessary codes and don't stop the execution flow

2024-06-10 10:17 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +    private void mergeLogFile(File file, FileWriter writer) {
change method name to mergeLogFiles or change it to more accurate one

2024-06-10 10:18 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +            String line;
Give the proper name for the variables

2024-06-10 10:23 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +    public static void main(String[] args) {
Make sure to use class level and method level comments

2024-06-12 12:37 UTC, vinodkadam22 requested changes

2024-06-12 12:37 UTC, vinodkadam22 commented on .idea/uiDesigner.xml
Do not commit .idea folder or any such files which have dependency for your local environment

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +package com.chandrakanthdemo;
Rename the package, do not name the package with individual name

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> + */
What is this comments ?

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +        File folder = new File(folderPath);
Rename the variable

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> +//folderPath = C:\elixrlabs\corejavapplication\logfiles
1. Try handling the Exception with proper error message.
2. And add a line after 61.
3. remove unnecessary comments.

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +            }
Try handling the Exception with proper error message.

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +            Thread.sleep(2000); // Simulating 2 seconds of processing time
Why Thred.sleep?

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +        }
Try handling the Exception with proper error message.

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/chandrakanthdemo/ProcessingTask.java
> +        return "";
Try handling the Exception with proper error message.
and move "" to constants

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/ProcessingTask.java
> +                    }
Write a separate method for this code.

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/ProcessingTask.java
> +            List<String> logs = logsByTimestampMap.get(timestamp);
Rename the variable

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
All the constants must be in Alphabetic order.
And create a separate Package for constants and move this class to it.
Remove unwanted lines

2024-06-12 12:37 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/utils/Validations.java
> +    /**
1. Give the proper name to this class
2. Move this class to sperate Validator package
3. Pls Provide correct and meaning full names to the variables 
4. Avoid using Static

2024-06-12 12:41 UTC, divya-sathyan commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
> +    public static final String NEW_LINE = "\n";
Refactor this NEW_LINE has NEW_LINE_CHAR

2024-06-12 12:47 UTC, SChandrakanth15 commented
Hi bro this is my old package I forgot to delete it. Please have a check on
package named "elixrlabs"

On Wed, Jun 12, 2024, 18:08 vinodkadam22 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On .idea/uiDesigner.xml
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636363432>
> :
>
> Do not commit .idea folder or any such files which have dependency for
> your local environment
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636365164>
> :
>
> > @@ -0,0 +1,61 @@
> +package com.chandrakanthdemo;
>
> Rename the package, do not name the package with individual name
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636365669>
> :
>
> > +/**
> + * jvsjgkkhlhe
> + * jhsgjhd
> + * hdg
> + */
>
> What is this comments ?
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636367123>
> :
>
> > +
> +    /**
> +     * jygwqdg
> +     * @param args
> +     */
> +    public static void main(String[] args) {
> +        System.out.println("Welcome to LogAggregator Tool");
> +        System.out.println("-------------------------------------------");
> +        Scanner scanner = new Scanner(System.in);//
> +
> +        // Ask user to input the folder path
> +        System.out.print("Enter the path to the folder containing log files: ");
> +        String folderPath = scanner.nextLine().trim();
> +        scanner.close();
> +        // Check if the provided path exists and is a directory
> +        File folder = new File(folderPath);
>
> Rename the variable
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636368219>
> :
>
> > +        Scanner scanner = new Scanner(System.in);//
> +
> +        // Ask user to input the folder path
> +        System.out.print("Enter the path to the folder containing log files: ");
> +        String folderPath = scanner.nextLine().trim();
> +        scanner.close();
> +        // Check if the provided path exists and is a directory
> +        File folder = new File(folderPath);
> +        if (!folder.exists() || !folder.isDirectory()) {
> +            System.err.println("please enter a valid folder");
> +            return;
> +        }
> +        // Show processing message
> +        System.out.println("Processing...");
> +        //to show the files in the folder
> +        File[] files = folder.listFiles();
>
> Rename the variable
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/LogAggregatorc.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636371191>
> :
>
> > +            } catch (InterruptedException e) {
> +                e.printStackTrace();
> +            }
> +        }
> +        System.out.println("\nProcessing completed.");
> +    }
> +}
> +//folderPath = C:\elixrlabs\corejavapplication\logfiles
>
>
>    1. Try handling the Exception with proper error message.
>    2. And add a line after 61.
>    3. remove unnecessary comments.
>
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/ProcessingTask.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636372616>
> :
>
> > +            } catch (IOException e) {
> +                e.printStackTrace();
> +            }
>
> Try handling the Exception with proper error message.
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/ProcessingTask.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636373276>
> :
>
> > +                    if (file.isFile()) {
> +                        System.out.println("Processing file: " + file.getName());
> +                        mergeLogFile(file, writer);
> +                    }
> +                }
> +                System.out.println("Logs files have been merged into merged_logs.txt");
> +            } catch (IOException e) {
> +                e.printStackTrace();
> +            }
> +        } else {
> +            System.out.println("Folder is empty.");
> +        }
> +
> +        // Simulate some processing time
> +        try {
> +            Thread.sleep(2000); // Simulating 2 seconds of processing time
>
> Why Thred.sleep?
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/ProcessingTask.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636373459>
> :
>
> > +        } catch (InterruptedException e) {
> +            e.printStackTrace();
> +        }
>
> Try handling the Exception with proper error message.
> ------------------------------
>
> In src/main/java/com/chandrakanthdemo/ProcessingTask.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636374736>
> :
>
> > +        } catch (IOException e) {
> +            e.printStackTrace();
> +        }
> +        return "";
>
> Try handling the Exception with proper error message.
> and move "" to constants
> ------------------------------
>
> In src/main/java/com/elixrlabs/ProcessingTask.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636376977>
> :
>
> > +                    try (BufferedReader reader = Files.newBufferedReader(file)) {
> +                        String line;
> +                        while ((line = reader.readLine()) != null) {
> +                            Matcher matcher = pattern.matcher(line);
> +                            if (matcher.find()) {
> +                                String timestamp = matcher.group();
> +                                logsByTimestampMap.computeIfAbsent(timestamp, k -> new ArrayList<>()).add(line);
> +                            }
> +                        }
> +                    }
>
> Write a separate method for this code.
> ------------------------------
>
> In src/main/java/com/elixrlabs/ProcessingTask.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636377432>
> :
>
> >          }
>
> -        // Simulate some processing time
> -        try {
> -            Thread.sleep(2000); // Simulating 2 seconds of processing time
> -        } catch (InterruptedException e) {
> -            e.printStackTrace();
> +        List<String> mergedLogs = new ArrayList<>();
> +        // Extract timestamps and sort
> +        List<String> timestamps = new ArrayList<>(logsByTimestampMap.keySet());
> +        Collections.sort(timestamps);
> +
> +        // Append logs sorted by timestamps
> +        for (String timestamp : timestamps) {
> +            List<String> logs = logsByTimestampMap.get(timestamp);
>
> Rename the variable
> ------------------------------
>
> On src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636379274>
> :
>
> All the constants must be in Alphabetic order.
> And create a separate Package for constants and move this class to it.
> Remove unwanted lines
> ------------------------------
>
> In src/main/java/com/elixrlabs/utils/Validations.java
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#discussion_r1636381448>
> :
>
> > +public class Validations {
> +    /**
>
>
>    1. Give the proper name to this class
>    2. Move this class to sperate Validator package
>    3. Pls Provide correct and meaning full names to the variables
>    4. Avoid using Static
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SChandrakanth15/LogAggregator/pull/1#pullrequestreview-2112857389>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BI5YWVZQLQ6JXA62XVGKB2LZHA6LXAVCNFSM6AAAAABJB4 [...]

2024-06-12 12:58 UTC, divya-sathyan commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
> +
Remove empty spaces

2024-06-12 13:02 UTC, divya-sathyan commented on src/main/java/com/elixrlabs/LogAggregator.java
Why the package name is elixrlabs 
Give proper naming logAggregatorTool

2024-06-12 13:04 UTC, divya-sathyan commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
why there are two packages?

2024-06-12 13:19 UTC, divya-sathyan commented on src/main/java/com/elixrlabs/ProcessingTask.java
> +        try (FileWriter writer = new FileWriter(outputPath)) {
For writer give the valid name

2024-06-13 06:44 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/ProcessingTask.java
> +                    }
Done have changed into another method called readLogsFromFile.

2024-06-13 06:52 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/ProcessingTask.java
> +            List<String> logs = logsByTimestampMap.get(timestamp);
Done changed the variable to "timestampLogs".

2024-06-13 07:01 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
Done changed the constants to the alphabetic order. 
and moved to the package called constants.
successfully removed all the unwanted lines.

2024-06-13 07:25 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/utils/Validations.java
> +    /**
1.changed the class name from "Validations " to "LogAggregatorValidator".
2.Done moved to a seperate validator package
3.Done changed the variable named 'directory' to 'fileDirectory'.
4.removed static keyword

2024-06-13 07:26 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
Done

2024-06-13 07:27 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
> +    public static final String UNDER_LINE = " -------------------------------------------";
Done

2024-06-13 07:27 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/utils/LogAggregatorConstants.java
> +
Done

2024-06-13 07:28 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/LogAggregator.java
because as per the industry standards we should keep our project name as with the company name , like com.elixrlabs.LogAggregator

2024-06-13 07:32 UTC, SChandrakanth15 commented on src/main/java/com/chandrakanthdemo/LogAggregatorc.java
Actually i forgotten to delete it it was my demo package.

2024-06-13 11:18 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/LogAggregatorTool.java
> +        if (folderPath == null) {
This check can be performed in validator 
Return the program with a valid message

2024-06-13 11:20 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/LogAggregatorTool.java
> +        while (true) {
Why while is always true ?

2024-06-13 11:22 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/ProcessingTask.java
> +public class ProcessingTask implements Callable<String> {
Improper class name
Rename it to more specific one

2024-06-13 11:24 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/ProcessingTask.java
> +        if (!validator.isNotNullOrEmpty(folderPath)) {
Remove these checks from Constructor

2024-06-13 11:25 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/ProcessingTask.java
> +                if (Files.isRegularFile(file)) {
What is a regular file ?

2024-06-13 11:26 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/reader/LogFileReader.java
> +    public static void readLogsFromFile(Path file, Pattern pattern, Map<String, List<String>> logsByTimestampMap) throws IOException {
Why it is static.

2024-06-13 11:28 UTC, vinodkadam22 requested changes

2024-06-13 11:28 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/logaggregator/LogAggregatorTool.java
> +        }
Avoid else block

2024-06-13 11:28 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/logaggregator/ProcessingTask.java
> +
Avoid class level args

2024-06-13 11:28 UTC, vinodkadam22 commented on src/main/java/com/elixrlabs/logaggregator/validator/LogAggregatorValidator.java
Rename the variables

2024-06-13 11:32 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/writer/LogFileWriter.java
> +    public static void writeLogsToFile(List<String> logs, String outputPath) throws IOException {
static is not allowed

2024-06-13 11:35 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/AuditTable.java
> +public class AuditTable {
Its the dto for audit table
Please rename the class

2024-06-13 11:36 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/Driver.java
> +            Class.forName("com.mysql.cj.jdbc.Driver");
Move db strings to DatabaseConstants

2024-06-13 11:37 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/Driver.java
> +            PreparedStatement preparedStatement =connection.prepareStatement("select * from audit");
Move sqls to constants

2024-06-13 11:38 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/Driver.java
> +            PreparedStatement preparedStatement =connection.prepareStatement("select * from audit");
Where is the code for data insertion ?
Without inserting the data how can u retrieve all

2024-06-14 07:18 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/LogAggregatorTool.java
> +        while (true) {
yes i have mentioned true because shiju added an another feature that if the user enter's wrong folderpath it should return's an error method and then again ask the user to enter the input folderpath. and if the user enters the correct path then it exits.

2024-06-14 09:17 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/LogAggregatorTool.java
> +        if (folderPath == null) {
yes done

2024-06-14 09:30 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/ProcessingTask.java
> +        if (!validator.isNotNullOrEmpty(folderPath)) {
Done

2024-06-14 09:46 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/ProcessingTask.java
> +                if (Files.isRegularFile(file)) {
isRegularFile() is a method of the java.nio.file.Files. and it is used to check if a given path refers to a regular file.  and  a regular file is  a typical file that containing data.

2024-06-14 10:12 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/reader/LogFileReader.java
> +    public static void readLogsFromFile(Path file, Pattern pattern, Map<String, List<String>> logsByTimestampMap) throws IOException {
i have changed it

2024-06-14 13:04 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/LogAggregatorTool.java
> +        }
Done

2024-06-14 13:36 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/writer/LogFileWriter.java
> +    public static void writeLogsToFile(List<String> logs, String outputPath) throws IOException {
done

2024-06-14 13:38 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/AuditTable.java
> +public class AuditTable {
done

2024-06-14 13:38 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/Driver.java
> +            Class.forName("com.mysql.cj.jdbc.Driver");
done

2024-06-14 13:38 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/Driver.java
> +            PreparedStatement preparedStatement =connection.prepareStatement("select * from audit");
done

2024-06-14 13:39 UTC, SChandrakanth15 commented on src/main/java/com/elixrlabs/logaggregator/jdbc/Driver.java
> +            PreparedStatement preparedStatement =connection.prepareStatement("select * from audit");
This file was not completed

2024-06-18 10:23 UTC, ashutosh-2609 commented on src/main/java/com/elixrlabs/logaggregator/LogProcessorTask.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
Add date format in string into the constants

2024-06-21 08:46 UTC, closed without merging